plugins {
    id 'java'
}

group = 'robbery'
version = '1.0'

repositories {
    mavenCentral()
    maven {
        name = "papermc-repo"
        url = "https://repo.papermc.io/repository/maven-public/"
    }
    maven {
        name = "sonatype"
        url = "https://oss.sonatype.org/content/groups/public/"
    }
    maven { url 'https://jitpack.io/' }
    maven { url = uri("https://repo.dmulloy2.net/repo/") }
    maven { url = 'https://repo.extendedclip.com/releases/' }
    maven { url 'https://repo.bg-software.com/repository/api/' }
    maven { url = uri("https://repo.codemc.org/repository/maven-public/") }
    maven { url 'https://nexus.bencodez.com/repository/maven-public/' }
    maven { url 'https://repo.spongepowered.org/maven' }
}

dependencies {
    compileOnly("io.papermc.paper:paper-api:1.21.4-R0.1-SNAPSHOT")
    compileOnly 'net.dmulloy2:ProtocolLib:5.4.0'
    compileOnly "com.github.MilkBowl:VaultAPI:1.7.1"
    compileOnly 'me.clip:placeholderapi:2.11.6'
    compileOnly 'com.bgsoftware:SuperiorSkyblockAPI:2025.1'
    compileOnly 'com.bencodez:votingplugin:6.18.7'
    compileOnly 'net.luckperms:api:5.4'
}

def targetJavaVersion = 21
java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'

    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        options.release.set(targetJavaVersion)
    }
}

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset 'UTF-8'
    filesMatching('plugin.yml') {
        expand props
    }
}
